# 用当前 shell，终端支持 256 色
set -g default-shell $SHELL
set -g default-terminal 'xterm-256color'

# 响应快一点（escape-time 0ms，对 vim 的 Esc 最友好）
set -s escape-time 0
set -g display-panes-time 2000
set -g display-time 2000

# 鼠标、滚动历史
set-option -g mouse on
set-option -g history-limit 20000

# 重载配置
bind r source-file ~/.tmux.conf \; display '~/.tmux.conf sourced'

# 复制：vi 模式，prefix + [ 进入，v 选中，y 复制
unbind p
setw -g mode-keys vi
bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# 切换 pane：前缀 + hjkl
bind k select-pane -U
bind j select-pane -D
bind h select-pane -L
bind l select-pane -R

# 状态栏：使用默认配色，只保留常用信息
set -as terminal-overrides ',*:Tc'
set -g status on
set -g status-interval 5
set -g status-left ' #S '
set -g status-left-length 30
set -g status-right ' #{=21:pane_current_path} | %m-%d %H:%M '
set -g status-right-length 60
set -g window-status-format ' #I:#W '
set -g window-status-current-format ' #I:#W* '
set -g window-status-separator ''
